[monitor]
monitor_side = 0
auto_switch_monitor_side = true

[episode]
opponent_agent = "selfplay"
eval_interval = 10
eval_opponent_type = "common_ai"

[[lineups.blue_camp]]
hero_id = 112

[[lineups.red_camp]]
hero_id = 112
